name: Deploy GitHub Pages
# 触发条件：在 push 到 main 分支后触发
on:
  push:
    branches:
      - main
# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 3、同步到 gitee 的仓库
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          # f3a45fb1fbfe877e43a3c22ad05c8b68
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:jiwei-hemeng/summary.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:jiwei-hemeng/summary.git


      